#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

uv run python manage.py collectstatic --noinput

exec python -m daphne -b 0.0.0.0 -p 8000 --access-log --proxy-headers config.asgi:application
